const { Schema, model } = require('mongoose')
const PitFormDataSchema = new Schema({
    _id: Schema.Types.ObjectId,
    teamNumber: Number,
    strategyOverall: String,
    strategyAprilTags: String,
    strategyLanguage: String,
    mechanicalProtectedElectronics: String,
    mechanicalSecuredBattery: String,
    mechanicalBatteryNum: Number,
    mechanicalBatteryOldest: String,
    mechanicalBatteryChargeNum: Number,
    mechanicalHaveCameras: Boolean,
    mechanicalHaveAuto: Boolean,
    mechanicalAutoInfo: String,
    mechanicalCubesLow: Boolean,
    mechanicalCubesMid: Boolean,
    mechanicalCubesHigh: Boolean,
    mechanicalConesLow: Boolean,
    mechanicalConesMid: Boolean,
    mechanicalConesHigh: Boolean,
    mechanicalAutoBalancingTools: String,
    mechanicalChargeStationInches: String,
    mechanicalFrameDimensions: String,
    mechanicalRobotIssues: String,
    generalStudentNum: Number,
    generalMentorNum: Number,
    generalRobotNum: Number,
    generalCameraUsage: String,
    generalDriveTrain: String,
    generalDriveTrainBrand: String,
    generalSwerveYears: String,
    generalSwerveFixLoctite: Boolean,
    generalSwerveFixShafts: Boolean,
    driveteamRobotCompliments: String,
    driveteamChanges: String,
    driveteamSameTeamMatch: Boolean,
    driveteamManipulationMech: String,
    driveteamStrongestValue: String,
    driveteamWeakestValue: String,
    driveteamExtraComments: String,
    driveteamDirectContact: String,
    robotImage: String,
}, { timestamps: true });

module.exports = model("FormData", PitFormDataSchema, "pitforms")