const { Schema, model } = require("mongoose");

const PitFormSchema = new Schema(
  {
    _id: Schema.Types.ObjectId,
    event: String,
    teamNumber: Number,
    usersName: String,
    robotImage: String,
    overallStrategy: String,
    aprilTags: Boolean,
    aprilTagsUse: String,
    protectedElectronics: String,
    batterySecured: String,
    cameras: Boolean,
    cameraUsage: String,
    drivetrainType: String,
    drivetrainBrand: String,
    backupSwerve: Boolean,
    complimentaryRobot: String,
    robotChanges: String,
    scoreL1: Boolean,
    scoreL2: Boolean,
    scoreL3: Boolean,
    scoreL4: Boolean,
    scoreProcessor: Boolean,
    scoreShallow: Boolean,
    scoreDeep: Boolean,
    pickupGround: Boolean,
    pickupSource: Boolean,
    pickupOther: Boolean,
    pickupOtherExplain: String,
    auto: Boolean,
    autoCount: String,
    idealAuto: String,
    canScoreSpeaker: Boolean,
    canScoreAmp: Boolean,
    canScoreTrap: Boolean,
    fitUnderStage: Boolean,
    climbInfo: String,
    humanPlayerInfo: String,
    robotIssues: String,
    preferredDriverStation: String,
    preferedHumanPlayerPlacement: String,
    strongestValue: String,
    weakestValue: String,
    extraComments: String,
  },
  { timestamps: true }
);

module.exports = model("PitForm", PitFormSchema, "PIT_FORMS");
